name: D3plus

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
- jekyll-redirect-from

permalink: /blog/:categories/:year/:month/:day/:title/

collections:
  docs:
    output: false
  examples:
    output: true
    permalink: examples/:path

defaults:
  - scope:
      type: examples
    values:
      layout: example
      width: 800

navigation:
# - text: Download
#   url: /d3plus.zip
#   icon: download
- text: Examples
  url: /examples/
  icon: code
- text: Documentation
  url: /docs/
  icon: book
# - text: Workshops
#   url: /workshops/
- text: Accessibility
  url: /accessibility/
  icon: universal-access
# - text: Blog
#   url: /blog/
#   icon: rss
- text: Github
  url: https://github.com/alexandersimoes/d3plus
  icon: github

workshops:
  nav_11_19_2013:
    title: "Workshop 1: November 19th, 2013"
    links:
    - text: Intro
      url: intro
    - text: D3js
      url: d3js
    - text: Data and Attributes
      url: d3plus
    - text: Tree Map
      url: tree_map
    - text: Stacked
      url: stacked
    - text: Pie Scatter
      url: pie_scatter/
    - text: Network
      url: network
    - text: Rings
      url: rings
    - text: Future Development
      url: future

  nav_11_29_2013:
    title: "Workshop 2: November 29th, 2013"
    links:
    - text: Intro
      url: intro
    - text: SVG
      url: svg
    - text: D3js
      url: d3js
    - text: Data and Attributes
      url: d3plus
    - text: Getting Started
      url: started
    - text: Tree Map
      url: tree_map
    - text: Stacked
      url: stacked
    - text: Pie Scatter
      url: pie_scatter/
    - text: Network
      url: network
    - text: Rings
      url: rings
    - text: Future Development
      url: future

  nav_03_19_2014:
    title: "Workshop 3: March 19th, 2014 (Networks)"
    links:
    - text: Intro
      url: intro
    - text: Local Environment
      url: env
    - text: Downloading D3plus
      url: download
    - text: Formatting Edges
      url: edges
    - text: Viz
      url: viz
    - text: Your Data
      url: your_data
    - text: Rings
      url: rings
    - text: Customizing
      url: customizing
    - text: Tree Map
      url: tree_map

  nav_04_03_2015:
    title: "Workshop 4: April 3rd, 2015 (Int'l Trade)"
    links:
    - text: Intro
      url: intro
    - text: Local Environment
      url: env
    - text: Downloading D3plus
      url: download
